[package]
name = "grathe"
version = "0.1.6"
edition = "2021"
authors = ["Alessio Zanga <alessio.zanga@outlook.it>"]
description = "A Rust implementation of a GRAph THEory library."
readme = "README.md"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/AlessioZanga/grathe"
repository = "https://github.com/AlessioZanga/grathe"
documentation = "https://docs.rs/grathe"
keywords = ["graph", "graph-algorithms", "graph-theory", "networks"]
categories = ["algorithms", "data-structures", "mathematics", "science"]

# See more keys and their definitions at:
# https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
delegate = "^0.6.1"
itertools = "^0.10.1"
log = {version = "^0.4.14", features = ["max_level_debug", "release_max_level_warn"]}
nalgebra = "^0.29.0"
nalgebra-sparse = "^0.5.0"
num-traits = "^0.2.14"
pest = "^2.1.3"
pest_derive = "^2.1.0"
thiserror = "^1.0.30"

[dev-dependencies]
all_asserts = "^2.3.0"
anyhow = "^1.0.51"
generic-tests = "^0.1.2"
tempfile = "^3.2.0"

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "./src/docs-header.html" ]
