on: [push]

name: benchmark

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Benchmark
        run: cargo bench --bench benchmarks -- --output-format bencher | tee output.txt
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ./cache
            ~/.cargo
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.toml') }}
      - name: Analyze
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'Benchmark'
          tool: 'cargo'
          output-file-path: output.txt
          external-data-json-path: ./cache/benchmark-data.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          alert-threshold: '200%'
          comment-on-alert: true
          alert-comment-cc-users: '@AlessioZanga'
