on: [push]

name: build

jobs:
  build:
    name: grathe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          components: rustfmt, clippy
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Publish
        if: github.ref == 'refs/heads/main'
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          cargo login "$TOKEN"
          cargo publish
