on: [push]

name: build

jobs:
  build:
    name: grathe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: actions-rs/toolchain@v1
        with:
          override: true
          toolchain: stable
          components: rustfmt, clippy
      - name: Check
        run: cargo check
      - name: Build
        run: cargo build
      - name: Test
        run: cargo test
      - name: Coverage
        env:
          CARGO_INCREMENTAL: 0
        run: |
          rustup override set nightly
          cargo install grcov
          RUSTFLAGS="-Z profile" cargo test
          grcov . --binary-path ./target/debug -s . -t lcov --branch --ignore *tests* --ignore-not-existing -o coverage
      - name: CodeCov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage
          flags: unittests
          fail_ci_if_error: true
      - name: Publish
        if: github.ref == 'refs/heads/main'
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          cargo login "$TOKEN"
          cargo publish
